"""add prompt column to webpage table

Revision ID: aa8102ba075a
Revises: dab749171719
Create Date: 2025-01-17 14:24:19.263676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa8102ba075a'
down_revision: Union[str, None] = 'dab749171719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webpage', sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webpage', 'prompt')
    # ### end Alembic commands ###
