"""add llm_response column to webpage

Revision ID: ec394dc0b476
Revises: aa8102ba075a
Create Date: 2025-01-29 15:58:26.928099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec394dc0b476'
down_revision: Union[str, None] = 'aa8102ba075a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webpage', sa.Column('llm_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webpage', 'llm_response')
    # ### end Alembic commands ###
